# JEKYLL
encoding: utf-8
exclude:
  - "signal-log"
gems:
  - jekyll-paginate
  - jekyll-auto-image

# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.monkinetic.blog" # the base hostname & protocol for your site

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /feed.xml

# THEME-SPECIFIC CONFIGURATION
theme_data:
  # Meta
  title: monkinetic .blog
  avatar: sivy_avatar_256.png
  gitlab_repo: steveivy/steveivy.gitlab.io
  # gravatar: 4fe0ff89158486e907c3a19ded9ac0df
  description: "Steve Ivy's weblog - Since 1999 - XV Ed." # used by search engines

  # Header and footer text
  header_text: >
   <p>Steve Ivy &mdash; Since 1999 &mdash; XV Ed.</p>
  footer_text: >
   <h3>Comment Policy</h3>
   <p>
   Webmentions and pingbacks are supported here, so share your thoughts on your blog
   and I'll probably get notified about it. You can also send me an email instead -
   steveivy @ gmail.com. Or hit me up on Twitter:
   <a href="https://twitter.com/steveivy">@steveivy</a> or Mastodon:
   <a href="https://toot.cafe/@sivy">@sivy@toot.cafe</a>.
   </p>
   <p>&copy; Copyright Steve Ivy, 1999-2017</p>

  # Icons
  rss: true
  email_address: steveivy@gmail.com  # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "sivy"
  # gitlab: "steveivy/steveivy.gitlab.io"
  google_plus:
  instagram:
  linkedin:  # Full URL
  mastodon: "https://toot.cafe/@sivy"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "steveivy"
  wordpress:
  youtube:

  service_links:
    -
      name: github
      link: "https://github.com/sivy/"
      icon: fa-github

    -
      name: toot.cafe
      link: "https://toot.cafe/@sivy"
      icon: "/img/mastodon_logo.svg"

    -
      name: mastodon.social
      link: "https://mastodon.social/@sivy"
      icon: "/img/mastodon_logo.svg"

    -
      name: twitter
      link: "https://twitter.com/steveivy"
      icon: fa-twitter

  # Scripts
  # google_analytics: # Tracking ID, e.g. "UA-000000-01"
  # disqus_shortname:
  # katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

  resist_sites:
    ACLU: https://www.aclu.org
    Southern Poverty Law Center: https://www.splcenter.org
    Electronic Frontier Foundation: https://www.eff.org

# PERMALINK
permalink: /:title.html

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
# markdown: MacroConverter
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

prose:
  rooturl: "_posts"
  siteurl: "https://www.monkinetic.blog"
  media: "images"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "type"
        field:
          element: "select"
          label: "Type"
          value: "post"
          options:
            - name: 'Post'
              value: 'post'
            - name: 'Note'
              value: 'note'
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Post Excerpt"
          help: "Short description for longer posts"
      - name: "feature-img"
        field:
          element: "text"
          label: "Feature Img"
          help: "image in the images/ folder"
